### ISSUE TITLE
Add a scenario to randomly kill pods based on a regexp

### ISSUE THREAD

**Issue by mffiedler** [openshift-scale/kraken#13]
Add a scenario to kill a random pod selected from pods matching a regexp.   We have a simple, but effective shell script in OpenShift testing that randomly takes out infra pods.   Combined with Cerberus (https://github.com/openshift-scale/cerberus) we can detect non-transient issues caused by such a scenario.

Example (in shell scripting):
```
#!/bin/bash
NUM=$1
SLEEP=$2
while true; do 
   echo "============"
   oc get pods --all-namespaces | grep openshift | grep Running| awk {'print $1" "$2'} | shuf -n $NUM | while read i; do oc delete pod -n $i --wait=false; done; sleep $SLEEP; 
done
```

```

**Comment by chaitanyaenr** [comment]
Fixed by https://github.com/openshift-scale/kraken/pull/16. Thanks to @paigerube14.
