### ISSUE TITLE
Scenarios will need updating with new powerfulseal code

### ISSUE THREAD

**Issue by paigerube14** [openshift-scale/kraken#19]
While I was looking at trying to add code to powerfulseal for the regex namespace issue I opened (https://github.com/bloomberg/powerfulseal/issues/274) I noticed that the latest python pip package is very outdated compared to the code in github. 

There are a couple of RC releases that you are able to install if given the version numbers. Seen [here](https://pypi.org/project/powerfulseal/#history)

Trying to test my code I had to completely rewrite the the pod kill scenario. As you can see in the documentation [here](https://pypi.org/project/powerfulseal/3.0.0rc9/) it no longer has the podScenario and nodeScenario sections, it is just one common scenarios section. 

These changes are not too huge but will have to be done at some point in the future. 

Examples: 
[2.9.0 scenario]( https://github.com/openshift-scale/kraken/blob/3ed95df78292be21be2851084011ec817ae18cfa/scenarios/regex_random_pod_kill.yml)
[3.0.* scenario](https://github.com/openshift-scale/kraken/blob/3ed95df78292be21be2851084011ec817ae18cfa/scenarios/regex_random_pod_kill2.yml)

We will need to make updates to our scenarios when the pip package updates from the current 2.9.0 version.

**Comment by chaitanyaenr** [comment]
Nice catch @paigerube14. Let's hard code the version in the requirements.txt to install the latest version ( 3.0.0rc9 ) provided it's stable and update the configs to use the latest syntax to avoid adding more configs following the old syntax from 2.9.0 version. Thoughts?

**Comment by paigerube14** [comment]
I think that's a good idea! From what I've seen there wasn't much difference between 3.0.0rc4, 3.0.0rc8, and 3.0.0rc9. I think if we set one of those numbers as the default and then we can make the scenario changes and then hopefully it won't have any more huge changes in the near future

**Comment by chaitanyaenr** [comment]
Fixed by https://github.com/openshift-scale/kraken/pull/20. Thanks @paigerube14.
