### ISSUE TITLE
kubernetes equivalent of oc commands

### ISSUE THREAD

**Issue by infa-anisrini** [openshift-scale/kraken#32]
I see that you have the following commands to stop kubelets in oc environment:

`oc debug node/" + node + " -- chroot /host systemctl stop kubelet`

What will be the kubectl equivalent of that ?

**Comment by mffiedler** [comment]
kubectl does not have a "debug node" capability.   The equivalent in kubernetes would be ssh-ing into node to stop the kubelet.

**Comment by infa-anisrini** [comment]
ok thanks, got it!!
