### ISSUE TITLE
Support for Azure cloud

### ISSUE THREAD

**Issue by wouter2397** [openshift-scale/kraken#36]
First thanks for making this tool available to the general public, it looks really awsome!

Is there already a roadmap for supporting different clouds, in our case specifically Azure?
If so can you provide any rough indication on when this would be added?

We use OpenShift on Azure and this tool look really awsome so that's why we would love to use this in our setup!

**Comment by mffiedler** [comment]
The pod killing scenarios (for Kubernetes, OpenShift or user pods) is currently supported on Azure and we are in the process of adding support for some Litmus scenarios which should also be supported on Azure - see PR #33 .   Only the node scenarios are currently AWS only.  If you want to start with the sample config file, you can just comment out the node scenarios.

We are looking at adding node scenarios for other clouds, but don't have a firm timeline yet.  We need to make sure the APIs provide all the functionality required.

**Comment by wouter2397** [comment]
Thank you @mffiedler for clarifying this.
We are still checking the implementation within our company but after that we will start with the pod scenario's.

Hopefully the Azure cloud will be added soon.

I will close this ticket.

**Comment by mffiedler** [comment]
@wouter2397 Glad to see your are looking at using Kraken.   Please open issues for any questions or problems as you work with it.
