### ISSUE TITLE
Modularize calls to scenarios in Kraken main() 

### ISSUE THREAD

**Issue by mffiedler** [openshift-scale/kraken#39]
From PR #38  :  This might be a good time to also separate out each different type of scenario into its own function. This might make it easier to read and add the many more types of scenarios that are being worked on as well.

This should be done after #37 merges and #38 is finalized.   @yashashreesuresh @paigerube14 @chaitanyaenr

**Comment by paigerube14** [comment]
Can we close this issue? Yashashree ended up adding this to her PR #38

**Comment by chaitanyaenr** [comment]
Yes, think we can go ahead and close this.
