### ISSUE TITLE
trying to deploy the image and it is not working  on openshift 

### ISSUE THREAD

**Issue by satishchennu1** [openshift-scale/kraken#48]
trying to deploy the image and it is not working  on openshift

**Comment by satishchennu1** [comment]
i am using openshift 4.5.17  on AWS . not able to deploy the docker file . 

docker build was successfull and while running pod i see issue 

2020-11-10 22:38:22,810 [INFO] Starting kraken
2020-11-10 22:38:22,817 [INFO] Initializing client to talk to the Kubernetes cluster
 _              _              
| | ___ __ __ _| | _____ _ __  
| |/ / '__/ _` | |/ / _ \ '_ \ 
|   <| | | (_| |   <  __/ | | |
|_|\_\_|  \__,_|_|\_\___|_| |_|
                               

Traceback (most recent call last):
  File "run_kraken.py", line 315, in <module>
    main(options.cfg)
  File "run_kraken.py", line 234, in main
    kubecli.initialize_clients(kubeconfig_path)
  File "/root/kraken/kraken/kubernetes/client.py", line 14, in initialize_clients
    config.load_kube_config(kubeconfig_path)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/config/kube_config.py", line 753, in load_kube_config
    persist_config=persist_config)
  File "/usr/local/lib/python3.6/site-packages/kubernetes/config/kube_config.py", line 711, in _get_kube_config_loader
    'Invalid kube-config file. '
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.

**Comment by mffiedler** [comment]
@paigerube14 @chaitanyaenr

**Comment by satishchennu1** [comment]
right now i have reconfigured everything now i get diffrent issue while pod getting initialized . 

right now pod is going to crashbackloop state . 

Traceback (most recent call last):
  File "run_kraken.py", line 312, in <module>
    main(options.cfg)
  File "run_kraken.py", line 234, in main
    kubecli.find_kraken_node()
  File "/root/kraken/kraken/kubernetes/client.py", line 166, in find_kraken_node
    pod_json = json.loads(pod_json_str)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by chaitanyaenr** [comment]
Hi @satishchennu1, can you share the config file with us so that we can try to reproduce it please? We had some infrastructure issues with kraken image building jobs, so the image ( quay.io/openshift-scale/kraken ) was not automatically being created with the latest bits. Sorry about that, we have resolved it now. Can you try running it again to see if that's the issue?

**Comment by chaitanyaenr** [comment]
@satishchennu1 Just a note that it's recommended to run Kraken outside the cluster to be resilient to the failures happening in the Kubernetes cluster. We can run it using podman or stanalone python application by specifying the kubeconfig to hit the API:https://github.com/openshift-scale/kraken/blob/master/docs/installation.md. Thoughts?

**Comment by satishchennu1** [comment]
here is the configfile , tried to run again still same issue 

kraken:
    kubeconfig_path: /root/.kube/config                    # Path to kubeconfig
    exit_on_failure: False                                 # Exit when a post action scenario fails
    chaos_scenarios:                                         # List of policies/chaos scenarios to load
        -   pod_scenarios:                                 # List of chaos pod scenarios to load
            - -    scenarios/etcd.yml
            - -    scenarios/regex_openshift_pod_kill.yml
              -    scenarios/post_action_regex.py
        -   node_scenarios:                                # List of chaos node scenarios to load
            -   scenarios/node_scenarios_example.yml
        -   pod_scenarios:
            - -    scenarios/openshift-apiserver.yml
            - -    scenarios/openshift-kube-apiserver.yml
        -   time_scenarios:                                # List of chaos time scenarios to load
            - scenarios/time_scenarios_example.yml

cerberus:
    cerberus_enabled: False                                # Enable it when cerberus is previously installed
    cerberus_url: http://0.0.0.0:8080                                         # When cerberus_enabled is set to True, provide the url where cerberus publishes go/no-go signal

tunings:
    wait_duration: 60                                      # Duration to wait between each chaos scenario
    iterations: 1                                          # Number of times to execute the scenarios
    daemon_mode: False                                     # Iterations are set to infinity which means that the kraken will cause chaos forever

**Comment by satishchennu1** [comment]
can i open ticket with redhat support on this .

**Comment by mffiedler** [comment]
Kraken is a community open source tool.  It is not supported by Red Hat.

**Comment by satishchennu1** [comment]
please close the issue after cleaning pip and python install resolved issue .
