### ISSUE TITLE
import yaml issue 

### ISSUE THREAD

**Issue by satishchennu1** [openshift-scale/kraken#51]
when i try to run command on regular one i see the issue 
[root@ip-10-201-36-93 cerberus]# python3 start_cerberus.py --config=config/config.yaml
Traceback (most recent call last):
  File "start_cerberus.py", line 5, in <module>
    import yaml
ImportError: No module named 'yaml'
[root@ip-10-201-36-93 cerberus]#
[root@ip-10-201-36-93 cerberus]#
[root@ip-10-201-36-93 cerberus]#
[root@ip-10-201-36-93 cerberus]#
[root@ip-10-201-36-93 cerberus]#

**Comment by chaitanyaenr** [comment]
@satishchennu1 Thanks for reporting the issue, https://github.com/openshift-scale/kraken/pull/52 fixes it. Thanks.
