### ISSUE TITLE
trying to run kraken using python3 having following issue 

### ISSUE THREAD

**Issue by satishchennu1** [openshift-scale/kraken#53]
[root@ip-00-000-00-00 kraken]# ls -lrt
total 15988
-rw-r-----. 1 root root 14421964 Feb 25  2015 Python-3.4.3.tar.xz
drwxr-x---. 3 root root       22 Nov 10 15:36 CI
-rw-r-----. 1 root root    11357 Nov 10 15:36 LICENSE
-rw-r-----. 1 root root     2352 Nov 10 15:36 README.md
drwxr-x---. 4 root root       84 Nov 10 15:36 ansible
drwxr-x---. 2 root root       88 Nov 10 15:36 containers
drwxr-x---. 2 root root     4096 Nov 10 15:36 docs
drwxr-x---. 6 root root       74 Nov 10 15:36 kraken
drwxr-x---. 2 root root       32 Nov 10 15:36 media
-rw-r-----. 1 root root      450 Nov 10 15:36 tox.ini
-rw-r-----. 1 root root       18 Nov 10 15:36 test-requirements.txt
-rw-r-----. 1 root root      297 Nov 10 15:36 setup.py
-rw-r-----. 1 root root     1099 Nov 10 15:36 setup.cfg
drwxr-x---. 2 root root     4096 Nov 10 15:36 scenarios
drwxr-x---. 2 root root        6 Nov 12 12:57 docker
drwxr-x---. 2 root root       46 Nov 12 14:27 config
-rw-r-----. 1 root root    13859 Nov 12 14:36 run_kraken.py
drwxr-x---. 5 root root       69 Nov 12 17:35 py36-venv
-rw-r-----. 1 root root  1886796 Nov 12 17:44 get-pip.py
-rw-r-----. 1 root root       93 Nov 12 17:52 requirements.txt

[root@ip-00-000-00-00 kraken]# python3 -V
Python 3.4.3

[root@ip-00-000-00-00 kraken]#
[root@ip-00-000-00-00 kraken]# pip3 -V
pip 20.2.4 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
[root@ip-00-000-00-00 kraken]# python3 -V
Python 3.4.3
[root@ip-00-000-00-00 kraken]# python -V
Python 3.6.8
[root@ip-00-000-00-00 kraken]#
[root@ip-00-000-00-00 kraken]#
[root@ip-00-000-00-00 kraken]# pip3 -V
pip 20.2.4 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)

[root@ip-00-000-00-00 kraken]# pip3 install -r requirements.txt
Collecting git+https://github.com/powerfulseal/powerfulseal.git (from -r requirements.txt (line 4))
  Cloning https://github.com/powerfulseal/powerfulseal.git to /tmp/pip-req-build-ipizx782
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied (use --upgrade to upgrade): powerfulseal==3.2.0 from git+https://github.com/powerfulseal/powerfulseal.git in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: datetime in /usr/local/lib64/python3.6/site-packages (from -r requirements.txt (line 1)) (4.3)
Requirement already satisfied: pyfiglet in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (0.8.post1)
Requirement already satisfied: PyYAML in /usr/local/lib64/python3.6/site-packages (from -r requirements.txt (line 3)) (5.3.1)
Requirement already satisfied: requests in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 5)) (2.25.0)
Requirement already satisfied: boto3 in /usr/local/lib/python3.6/site-packages (from -r requirements.txt (line 6)) (1.16.16)
Requirement already satisfied: datadog<1.0.0,>=0.29.0 in /usr/local/lib/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (0.39.0)
Requirement already satisfied: python-dateutil<2.7.0,>=2.5.3 in /usr/local/lib/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (2.6.1)
Requirement already satisfied: coloredlogs<11.0.0,>=10.0.0 in /usr/local/lib/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (10.0)
Requirement already satisfied: azure-mgmt-resource<3.0.0,>=2.2.0 in /usr/local/lib/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (2.2.0)
Requirement already satisfied: google-api-python-client>=1.7.8 in /usr/local/lib/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (1.12.5)
Requirement already satisfied: google-auth>=1.6.2 in /usr/local/lib/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (1.23.0)
Requirement already satisfied: ConfigArgParse<1,>=0.11.0 in /usr/local/lib/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (0.15.2)
Requirement already satisfied: kubernetes==12.0.0a1 in /usr/local/lib/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (12.0.0a1)
Requirement already satisfied: future<1,>=0.16.0 in /usr/local/lib/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (0.18.2)
Requirement already satisfied: openstacksdk<1,>=0.10.0 in /usr/local/lib/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (0.51.0)
Requirement already satisfied: oauth2client>=4.1.3 in /usr/local/lib/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (4.1.3)
Requirement already satisfied: jsonschema<4,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (3.2.0)
Requirement already satisfied: Flask<2,>=1.0.0 in /usr/local/lib/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (1.1.2)
Requirement already satisfied: prometheus-client<0.4.0,>=0.3.0 in /usr/local/lib/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (0.3.1)
Requirement already satisfied: paramiko<3,>=2.5.0 in /usr/local/lib/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (2.7.2)
Requirement already satisfied: termcolor<2,>=1.1.0 in /usr/local/lib/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (1.1.0)
Requirement already satisfied: azure-common<2.0.0,>=1.1.23 in /usr/local/lib/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (1.1.26)
Requirement already satisfied: google-auth-httplib2>=0.0.3 in /usr/local/lib/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (0.0.4)
Requirement already satisfied: flask-cors<4,>=3.0.6 in /usr/local/lib64/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (3.0.9)
Requirement already satisfied: azure-mgmt-network<3.0.0,>=2.7.0 in /usr/local/lib/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (2.7.0)
Requirement already satisfied: spur<1,>=0.3.20 in /usr/local/lib/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (0.3.22)
Requirement already satisfied: azure-mgmt-compute<5.0.0,>=4.6.2 in /usr/local/lib/python3.6/site-packages (from powerfulseal==3.2.0->-r requirements.txt (line 4)) (4.6.2)
Requirement already satisfied: zope.interface in /usr/local/lib64/python3.6/site-packages (from datetime->-r requirements.txt (line 1)) (5.2.0)
Requirement already satisfied: pytz in /usr/local/lib/python3.6/site-packages (from datetime->-r requirements.txt (line 1)) (2020.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests->-r requirements.txt (line 5)) (1.26.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests->-r requirements.txt (line 5)) (2020.11.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests->-r requirements.txt (line 5)) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests->-r requirements.txt (line 5)) (2.10)
Requirement already satisfied: botocore<1.20.0,>=1.19.16 in /usr/local/lib/python3.6/site-packages (from boto3->-r requirements.txt (line 6)) (1.19.16)
Requirement already satisfied: s3transfer<0.4.0,>=0.3.0 in /usr/local/lib/python3.6/site-packages (from boto3->-r requirements.txt (line 6)) (0.3.3)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /usr/local/lib/python3.6/site-packages (from boto3->-r requirements.txt (line 6)) (0.10.0)
Requirement already satisfied: decorator>=3.3.2 in /usr/local/lib/python3.6/site-packages (from datadog<1.0.0,>=0.29.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (4.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.6/site-packages (from python-dateutil<2.7.0,>=2.5.3->powerfulseal==3.2.0->-r requirements.txt (line 4)) (1.15.0)
Requirement already satisfied: humanfriendly>=4.7 in /usr/local/lib/python3.6/site-packages (from coloredlogs<11.0.0,>=10.0.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (8.2)
Requirement already satisfied: msrest>=0.5.0 in /usr/local/lib/python3.6/site-packages (from azure-mgmt-resource<3.0.0,>=2.2.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (0.6.19)
Requirement already satisfied: msrestazure<2.0.0,>=0.4.32 in /usr/local/lib/python3.6/site-packages (from azure-mgmt-resource<3.0.0,>=2.2.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (0.6.4)
Requirement already satisfied: google-api-core<2dev,>=1.21.0 in /usr/local/lib/python3.6/site-packages (from google-api-python-client>=1.7.8->powerfulseal==3.2.0->-r requirements.txt (line 4)) (1.23.0)
Requirement already satisfied: httplib2<1dev,>=0.15.0 in /usr/local/lib/python3.6/site-packages (from google-api-python-client>=1.7.8->powerfulseal==3.2.0->-r requirements.txt (line 4)) (0.18.1)
Requirement already satisfied: uritemplate<4dev,>=3.0.0 in /usr/local/lib/python3.6/site-packages (from google-api-python-client>=1.7.8->powerfulseal==3.2.0->-r requirements.txt (line 4)) (3.0.1)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.6/site-packages (from google-auth>=1.6.2->powerfulseal==3.2.0->-r requirements.txt (line 4)) (0.2.8)
Requirement already satisfied: setuptools>=40.3.0 in /usr/local/lib/python3.6/site-packages (from google-auth>=1.6.2->powerfulseal==3.2.0->-r requirements.txt (line 4)) (50.3.2)
Requirement already satisfied: rsa<5,>=3.1.4; python_version >= "3.5" in /usr/local/lib/python3.6/site-packages (from google-auth>=1.6.2->powerfulseal==3.2.0->-r requirements.txt (line 4)) (4.6)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.6/site-packages (from google-auth>=1.6.2->powerfulseal==3.2.0->-r requirements.txt (line 4)) (4.1.1)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.6/site-packages (from kubernetes==12.0.0a1->powerfulseal==3.2.0->-r requirements.txt (line 4)) (1.3.0)
Requirement already satisfied: websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 in /usr/local/lib/python3.6/site-packages (from kubernetes==12.0.0a1->powerfulseal==3.2.0->-r requirements.txt (line 4)) (0.57.0)
Requirement already satisfied: keystoneauth1>=3.18.0 in /usr/local/lib/python3.6/site-packages (from openstacksdk<1,>=0.10.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (4.2.1)
Requirement already satisfied: pbr!=2.1.0,>=2.0.0 in /usr/local/lib/python3.6/site-packages (from openstacksdk<1,>=0.10.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (5.5.1)
Requirement already satisfied: munch>=2.1.0 in /usr/local/lib/python3.6/site-packages (from openstacksdk<1,>=0.10.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (2.5.0)
Requirement already satisfied: importlib-metadata>=1.7.0; python_version < "3.8" in /usr/local/lib/python3.6/site-packages (from openstacksdk<1,>=0.10.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (2.0.0)
Requirement already satisfied: dogpile.cache>=0.6.5 in /usr/local/lib/python3.6/site-packages (from openstacksdk<1,>=0.10.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (1.0.2)
Requirement already satisfied: netifaces>=0.10.4 in /usr/local/lib64/python3.6/site-packages (from openstacksdk<1,>=0.10.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (0.10.9)
Requirement already satisfied: jsonpatch!=1.20,>=1.16 in /usr/local/lib/python3.6/site-packages (from openstacksdk<1,>=0.10.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (1.26)
Requirement already satisfied: appdirs>=1.3.0 in /usr/local/lib/python3.6/site-packages (from openstacksdk<1,>=0.10.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (1.4.4)
Requirement already satisfied: iso8601>=0.1.11 in /usr/local/lib/python3.6/site-packages (from openstacksdk<1,>=0.10.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (0.1.13)
Requirement already satisfied: requestsexceptions>=1.2.0 in /usr/local/lib/python3.6/site-packages (from openstacksdk<1,>=0.10.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (1.4.0)
Requirement already satisfied: cryptography>=2.7 in /usr/local/lib64/python3.6/site-packages (from openstacksdk<1,>=0.10.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (3.2.1)
Requirement already satisfied: os-service-types>=1.7.0 in /usr/local/lib/python3.6/site-packages (from openstacksdk<1,>=0.10.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (1.7.0)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.6/site-packages (from oauth2client>=4.1.3->powerfulseal==3.2.0->-r requirements.txt (line 4)) (0.4.8)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.6/site-packages (from jsonschema<4,>=3.0.2->powerfulseal==3.2.0->-r requirements.txt (line 4)) (20.3.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /usr/local/lib64/python3.6/site-packages (from jsonschema<4,>=3.0.2->powerfulseal==3.2.0->-r requirements.txt (line 4)) (0.17.3)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.6/site-packages (from Flask<2,>=1.0.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (2.11.2)
Requirement already satisfied: Werkzeug>=0.15 in /usr/local/lib/python3.6/site-packages (from Flask<2,>=1.0.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (1.0.1)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.6/site-packages (from Flask<2,>=1.0.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (1.1.0)
Requirement already satisfied: click>=5.1 in /usr/local/lib/python3.6/site-packages (from Flask<2,>=1.0.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (7.1.2)
Requirement already satisfied: pynacl>=1.0.1 in /usr/local/lib64/python3.6/site-packages (from paramiko<3,>=2.5.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (1.4.0)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/local/lib64/python3.6/site-packages (from paramiko<3,>=2.5.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (3.2.0)
Requirement already satisfied: isodate>=0.6.0 in /usr/local/lib/python3.6/site-packages (from msrest>=0.5.0->azure-mgmt-resource<3.0.0,>=2.2.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (0.6.0)
Requirement already satisfied: adal<2.0.0,>=0.6.0 in /usr/local/lib/python3.6/site-packages (from msrestazure<2.0.0,>=0.4.32->azure-mgmt-resource<3.0.0,>=2.2.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (1.2.5)
Requirement already satisfied: protobuf>=3.12.0 in /usr/local/lib64/python3.6/site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client>=1.7.8->powerfulseal==3.2.0->-r requirements.txt (line 4)) (3.13.0)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /usr/local/lib/python3.6/site-packages (from google-api-core<2dev,>=1.21.0->google-api-python-client>=1.7.8->powerfulseal==3.2.0->-r requirements.txt (line 4)) (1.52.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.6/site-packages (from requests-oauthlib->kubernetes==12.0.0a1->powerfulseal==3.2.0->-r requirements.txt (line 4)) (3.1.0)
Requirement already satisfied: stevedore>=1.20.0 in /usr/local/lib/python3.6/site-packages (from keystoneauth1>=3.18.0->openstacksdk<1,>=0.10.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (3.2.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/site-packages (from importlib-metadata>=1.7.0; python_version < "3.8"->openstacksdk<1,>=0.10.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (3.4.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.6/site-packages (from jsonpatch!=1.20,>=1.16->openstacksdk<1,>=0.10.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (2.0)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/local/lib64/python3.6/site-packages (from cryptography>=2.7->openstacksdk<1,>=0.10.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (1.14.3)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib64/python3.6/site-packages (from Jinja2>=2.10.1->Flask<2,>=1.0.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (1.1.1)
Requirement already satisfied: PyJWT>=1.0.0 in /usr/local/lib/python3.6/site-packages (from adal<2.0.0,>=0.6.0->msrestazure<2.0.0,>=0.4.32->azure-mgmt-resource<3.0.0,>=2.2.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (1.7.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.7->openstacksdk<1,>=0.10.0->powerfulseal==3.2.0->-r requirements.txt (line 4)) (2.20)
Building wheels for collected packages: powerfulseal
  Building wheel for powerfulseal (PEP 517) ... done
  Created wheel for powerfulseal: filename=powerfulseal-3.2.0-py3-none-any.whl size=156211 sha256=adf9ad79cc8f30cb888ec0fc63bb69bdbbd9bc964980469319342c94c303c0bc
  Stored in directory: /tmp/pip-ephem-wheel-cache-rk3agc6k/wheels/2d/cf/51/8de7d61c30ff637fca2222e4ba67d69cc9f1f8c6f419a0ee0d
Successfully built powerfulseal

[root@ip-00-000-00-00 ~]# vi myfile
[root@ip-00-000-00-00 ~]# python
Python 3.6.8 (default, Aug 13 2020, 07:46:32)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> f = open('myfile')
>>> y = **yaml.**load(f)
__main__:1: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
>>> print(y)
this is satish

**[root@ip-00-000-00-00 kraken]# python3 run_kraken.py --config=config/config.yaml
Traceback (most recent call last):
  File "run_kraken.py", line 7, in <module>
    import yaml
ImportError: No module named 'yaml'**

**Comment by satishchennu1** [comment]
here are the contents of requirement.txt 
[root@ kraken]# cat requirements.txt
datetime
pyfiglet
PyYAML
git+https://github.com/powerfulseal/powerfulseal.git
requests
boto3

**Comment by satishchennu1** [comment]
any help on this

**Comment by paigerube14** [comment]
Are you able to give the output of both of the following commands:
`python -m pip list` and `python3 -m pip list`

It's a little confusing because I do see you have pyyaml installed.

**Comment by chaitanyaenr** [comment]
Looks like multiple versions of python3 are installed on the system, we can uninstall one of it or try $ python3 -m pip install pyyaml.

**Comment by satishchennu1** [comment]
thanks now i spinned new ec2 and reinstalled everythng , it works like charm

**Comment by chaitanyaenr** [comment]
Closing this as the issues is resolved. Thanks.
