### ISSUE TITLE
Node chaos scenarios

### ISSUE THREAD

**Issue by chaitanyaenr** [openshift-scale/kraken#8]
It's important to check how Kubernetes/OpenShift is dealing with the node failures, the failures can be a node termination or stop/shut down. The nodes can be terminated by hitting the cloud platform API on top of which OpenShift has been deployed ( AWS, GCP, Azure e.t.c ).

Kraken can accept a config from the user with the details including role/selector of the node to kill ( Master/node-role.kubernetes.io/master, Worker/node-role.kubernetes.io/worker, Infra/node-role.kubernetes.io/infra), number of nodes to kill and wait between each kill and act accordingly.

**Comment by mffiedler** [comment]
Some potential node failure scenarios:
- remove instance via cloud API
- "normal" node reboot (e.g. after applying patch for kernel CVE)
- extended (1 hour+) node shutdown for lab maintenance
- stop kubelet
- node crash (fork bomb or "echo c > /proc/sysrq-trigger")
- node SDN isolation from cluster
