### ISSUE TITLE
Run containerized kraken as a kubernetes/openshift deployment

### ISSUE THREAD

**Issue by mffiedler** [openshift-scale/kraken#9]
Further improve the ease of use of containerized kraken by providing an image on quay.io and creating a kubernetes or openshift deployment to run it.   Config can be provided via configmap.

**Comment by chaitanyaenr** [comment]
When we run Kraken/Cerberus as a Kubernetes/OpenShift object, there might be cases where the pod which is running the tool might get disrupted unless we add a way to blacklist it during the run. For instance, we might not get the results from the pod running Kraken or Cerberus when the API iteself is down. When we run them external to OpenShift, we can get a signal and catch test failures even when the API is down. Thoughts?

But agree that we might need to support both - running it internal/external to the cluster to improve the ease of use and users can pick the option depending on the use case.

**Comment by chaitanyaenr** [comment]
We can do something similar to https://github.com/openshift-scale/cerberus/tree/master/containers keeping in mind to avoid killing anything in namespace/node with kraken running.

**Comment by chaitanyaenr** [comment]
@paigerube14 do you want to pick this?

**Comment by chaitanyaenr** [comment]
Fixed by https://github.com/openshift-scale/kraken/pull/24. Thanks @paigerube14.
